//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PythonParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GameVM.Compiler.Python.ANTLR {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PythonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPythonParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.file_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_input([NotNull] PythonParser.File_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.file_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_input([NotNull] PythonParser.File_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.interactive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteractive([NotNull] PythonParser.InteractiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.interactive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteractive([NotNull] PythonParser.InteractiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval([NotNull] PythonParser.EvalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval([NotNull] PythonParser.EvalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.func_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_type([NotNull] PythonParser.Func_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.func_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_type([NotNull] PythonParser.Func_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_input([NotNull] PythonParser.Fstring_inputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_input([NotNull] PythonParser.Fstring_inputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] PythonParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] PythonParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] PythonParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] PythonParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.statement_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_newline([NotNull] PythonParser.Statement_newlineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.statement_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_newline([NotNull] PythonParser.Statement_newlineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.simple_stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_stmts([NotNull] PythonParser.Simple_stmtsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.simple_stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_stmts([NotNull] PythonParser.Simple_stmtsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_stmt([NotNull] PythonParser.Simple_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_stmt([NotNull] PythonParser.Simple_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_stmt([NotNull] PythonParser.Compound_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_stmt([NotNull] PythonParser.Compound_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] PythonParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] PythonParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.annotated_rhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotated_rhs([NotNull] PythonParser.Annotated_rhsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.annotated_rhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotated_rhs([NotNull] PythonParser.Annotated_rhsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.augassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAugassign([NotNull] PythonParser.AugassignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.augassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAugassign([NotNull] PythonParser.AugassignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] PythonParser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] PythonParser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.raise_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaise_stmt([NotNull] PythonParser.Raise_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.raise_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaise_stmt([NotNull] PythonParser.Raise_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.global_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobal_stmt([NotNull] PythonParser.Global_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.global_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobal_stmt([NotNull] PythonParser.Global_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.nonlocal_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonlocal_stmt([NotNull] PythonParser.Nonlocal_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.nonlocal_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonlocal_stmt([NotNull] PythonParser.Nonlocal_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.del_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDel_stmt([NotNull] PythonParser.Del_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.del_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDel_stmt([NotNull] PythonParser.Del_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.yield_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield_stmt([NotNull] PythonParser.Yield_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.yield_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield_stmt([NotNull] PythonParser.Yield_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.assert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssert_stmt([NotNull] PythonParser.Assert_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.assert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssert_stmt([NotNull] PythonParser.Assert_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_stmt([NotNull] PythonParser.Import_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_stmt([NotNull] PythonParser.Import_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_name([NotNull] PythonParser.Import_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_name([NotNull] PythonParser.Import_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_from([NotNull] PythonParser.Import_fromContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_from([NotNull] PythonParser.Import_fromContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_from_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_from_targets([NotNull] PythonParser.Import_from_targetsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_from_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_from_targets([NotNull] PythonParser.Import_from_targetsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_from_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_from_as_names([NotNull] PythonParser.Import_from_as_namesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_from_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_from_as_names([NotNull] PythonParser.Import_from_as_namesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.import_from_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_from_as_name([NotNull] PythonParser.Import_from_as_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.import_from_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_from_as_name([NotNull] PythonParser.Import_from_as_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.dotted_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_as_names([NotNull] PythonParser.Dotted_as_namesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.dotted_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_as_names([NotNull] PythonParser.Dotted_as_namesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.dotted_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_as_name([NotNull] PythonParser.Dotted_as_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.dotted_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_as_name([NotNull] PythonParser.Dotted_as_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.dotted_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_name([NotNull] PythonParser.Dotted_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.dotted_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_name([NotNull] PythonParser.Dotted_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] PythonParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] PythonParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecorators([NotNull] PythonParser.DecoratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecorators([NotNull] PythonParser.DecoratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.class_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_def([NotNull] PythonParser.Class_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.class_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_def([NotNull] PythonParser.Class_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.class_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_def_raw([NotNull] PythonParser.Class_def_rawContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.class_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_def_raw([NotNull] PythonParser.Class_def_rawContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_def([NotNull] PythonParser.Function_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_def([NotNull] PythonParser.Function_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.function_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_def_raw([NotNull] PythonParser.Function_def_rawContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.function_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_def_raw([NotNull] PythonParser.Function_def_rawContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] PythonParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] PythonParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] PythonParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] PythonParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlash_no_default([NotNull] PythonParser.Slash_no_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlash_no_default([NotNull] PythonParser.Slash_no_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlash_with_default([NotNull] PythonParser.Slash_with_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlash_with_default([NotNull] PythonParser.Slash_with_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_etc([NotNull] PythonParser.Star_etcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_etc([NotNull] PythonParser.Star_etcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKwds([NotNull] PythonParser.KwdsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKwds([NotNull] PythonParser.KwdsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_no_default([NotNull] PythonParser.Param_no_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_no_default([NotNull] PythonParser.Param_no_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param_no_default_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_no_default_star_annotation([NotNull] PythonParser.Param_no_default_star_annotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param_no_default_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_no_default_star_annotation([NotNull] PythonParser.Param_no_default_star_annotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_with_default([NotNull] PythonParser.Param_with_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_with_default([NotNull] PythonParser.Param_with_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_maybe_default([NotNull] PythonParser.Param_maybe_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_maybe_default([NotNull] PythonParser.Param_maybe_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] PythonParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] PythonParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.param_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_star_annotation([NotNull] PythonParser.Param_star_annotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.param_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_star_annotation([NotNull] PythonParser.Param_star_annotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] PythonParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] PythonParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_annotation([NotNull] PythonParser.Star_annotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_annotation([NotNull] PythonParser.Star_annotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.default_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_assignment([NotNull] PythonParser.Default_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.default_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_assignment([NotNull] PythonParser.Default_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] PythonParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] PythonParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.elif_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElif_stmt([NotNull] PythonParser.Elif_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.elif_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElif_stmt([NotNull] PythonParser.Elif_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_block([NotNull] PythonParser.Else_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_block([NotNull] PythonParser.Else_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_stmt([NotNull] PythonParser.While_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_stmt([NotNull] PythonParser.While_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_stmt([NotNull] PythonParser.For_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_stmt([NotNull] PythonParser.For_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.with_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_stmt([NotNull] PythonParser.With_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.with_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_stmt([NotNull] PythonParser.With_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.with_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWith_item([NotNull] PythonParser.With_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.with_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWith_item([NotNull] PythonParser.With_itemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.try_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTry_stmt([NotNull] PythonParser.Try_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.try_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTry_stmt([NotNull] PythonParser.Try_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.except_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExcept_block([NotNull] PythonParser.Except_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.except_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExcept_block([NotNull] PythonParser.Except_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.except_star_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExcept_star_block([NotNull] PythonParser.Except_star_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.except_star_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExcept_star_block([NotNull] PythonParser.Except_star_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.finally_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinally_block([NotNull] PythonParser.Finally_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.finally_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinally_block([NotNull] PythonParser.Finally_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.match_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatch_stmt([NotNull] PythonParser.Match_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.match_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatch_stmt([NotNull] PythonParser.Match_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.subject_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubject_expr([NotNull] PythonParser.Subject_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.subject_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubject_expr([NotNull] PythonParser.Subject_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.case_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase_block([NotNull] PythonParser.Case_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.case_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase_block([NotNull] PythonParser.Case_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGuard([NotNull] PythonParser.GuardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGuard([NotNull] PythonParser.GuardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatterns([NotNull] PythonParser.PatternsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatterns([NotNull] PythonParser.PatternsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern([NotNull] PythonParser.PatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern([NotNull] PythonParser.PatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.as_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAs_pattern([NotNull] PythonParser.As_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.as_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAs_pattern([NotNull] PythonParser.As_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.or_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_pattern([NotNull] PythonParser.Or_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.or_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_pattern([NotNull] PythonParser.Or_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.closed_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClosed_pattern([NotNull] PythonParser.Closed_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.closed_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClosed_pattern([NotNull] PythonParser.Closed_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.literal_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_pattern([NotNull] PythonParser.Literal_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.literal_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_pattern([NotNull] PythonParser.Literal_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.literal_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_expr([NotNull] PythonParser.Literal_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.literal_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_expr([NotNull] PythonParser.Literal_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.complex_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex_number([NotNull] PythonParser.Complex_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.complex_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex_number([NotNull] PythonParser.Complex_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_number([NotNull] PythonParser.Signed_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_number([NotNull] PythonParser.Signed_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.signed_real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_real_number([NotNull] PythonParser.Signed_real_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.signed_real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_real_number([NotNull] PythonParser.Signed_real_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReal_number([NotNull] PythonParser.Real_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReal_number([NotNull] PythonParser.Real_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.imaginary_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImaginary_number([NotNull] PythonParser.Imaginary_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.imaginary_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImaginary_number([NotNull] PythonParser.Imaginary_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.capture_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCapture_pattern([NotNull] PythonParser.Capture_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.capture_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCapture_pattern([NotNull] PythonParser.Capture_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.pattern_capture_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern_capture_target([NotNull] PythonParser.Pattern_capture_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.pattern_capture_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern_capture_target([NotNull] PythonParser.Pattern_capture_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWildcard_pattern([NotNull] PythonParser.Wildcard_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWildcard_pattern([NotNull] PythonParser.Wildcard_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_pattern([NotNull] PythonParser.Value_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_pattern([NotNull] PythonParser.Value_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttr([NotNull] PythonParser.AttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttr([NotNull] PythonParser.AttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.name_or_attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName_or_attr([NotNull] PythonParser.Name_or_attrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.name_or_attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName_or_attr([NotNull] PythonParser.Name_or_attrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.group_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_pattern([NotNull] PythonParser.Group_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.group_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_pattern([NotNull] PythonParser.Group_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSequence_pattern([NotNull] PythonParser.Sequence_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSequence_pattern([NotNull] PythonParser.Sequence_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.open_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpen_sequence_pattern([NotNull] PythonParser.Open_sequence_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.open_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpen_sequence_pattern([NotNull] PythonParser.Open_sequence_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.maybe_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaybe_sequence_pattern([NotNull] PythonParser.Maybe_sequence_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.maybe_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaybe_sequence_pattern([NotNull] PythonParser.Maybe_sequence_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.maybe_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMaybe_star_pattern([NotNull] PythonParser.Maybe_star_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.maybe_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMaybe_star_pattern([NotNull] PythonParser.Maybe_star_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_pattern([NotNull] PythonParser.Star_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_pattern([NotNull] PythonParser.Star_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.mapping_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapping_pattern([NotNull] PythonParser.Mapping_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.mapping_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapping_pattern([NotNull] PythonParser.Mapping_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.items_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItems_pattern([NotNull] PythonParser.Items_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.items_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItems_pattern([NotNull] PythonParser.Items_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.key_value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey_value_pattern([NotNull] PythonParser.Key_value_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.key_value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey_value_pattern([NotNull] PythonParser.Key_value_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.double_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble_star_pattern([NotNull] PythonParser.Double_star_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.double_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble_star_pattern([NotNull] PythonParser.Double_star_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.class_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_pattern([NotNull] PythonParser.Class_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.class_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_pattern([NotNull] PythonParser.Class_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.positional_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositional_patterns([NotNull] PythonParser.Positional_patternsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.positional_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositional_patterns([NotNull] PythonParser.Positional_patternsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.keyword_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_patterns([NotNull] PythonParser.Keyword_patternsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.keyword_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_patterns([NotNull] PythonParser.Keyword_patternsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.keyword_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_pattern([NotNull] PythonParser.Keyword_patternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.keyword_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_pattern([NotNull] PythonParser.Keyword_patternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_alias([NotNull] PythonParser.Type_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_alias([NotNull] PythonParser.Type_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_params([NotNull] PythonParser.Type_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_params([NotNull] PythonParser.Type_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_param_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_param_seq([NotNull] PythonParser.Type_param_seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_param_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_param_seq([NotNull] PythonParser.Type_param_seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_param([NotNull] PythonParser.Type_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_param([NotNull] PythonParser.Type_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_param_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_param_bound([NotNull] PythonParser.Type_param_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_param_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_param_bound([NotNull] PythonParser.Type_param_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressions([NotNull] PythonParser.ExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressions([NotNull] PythonParser.ExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] PythonParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] PythonParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.yield_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYield_expr([NotNull] PythonParser.Yield_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.yield_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYield_expr([NotNull] PythonParser.Yield_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_expressions([NotNull] PythonParser.Star_expressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_expressions([NotNull] PythonParser.Star_expressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_expression([NotNull] PythonParser.Star_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_expression([NotNull] PythonParser.Star_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_named_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_named_expressions([NotNull] PythonParser.Star_named_expressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_named_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_named_expressions([NotNull] PythonParser.Star_named_expressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_named_expression([NotNull] PythonParser.Star_named_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_named_expression([NotNull] PythonParser.Star_named_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_expression([NotNull] PythonParser.Assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_expression([NotNull] PythonParser.Assignment_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamed_expression([NotNull] PythonParser.Named_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamed_expression([NotNull] PythonParser.Named_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjunction([NotNull] PythonParser.DisjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjunction([NotNull] PythonParser.DisjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] PythonParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] PythonParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.inversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInversion([NotNull] PythonParser.InversionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.inversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInversion([NotNull] PythonParser.InversionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] PythonParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] PythonParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.compare_op_bitwise_or_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompare_op_bitwise_or_pair([NotNull] PythonParser.Compare_op_bitwise_or_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.compare_op_bitwise_or_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompare_op_bitwise_or_pair([NotNull] PythonParser.Compare_op_bitwise_or_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.eq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEq_bitwise_or([NotNull] PythonParser.Eq_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.eq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEq_bitwise_or([NotNull] PythonParser.Eq_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.noteq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoteq_bitwise_or([NotNull] PythonParser.Noteq_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.noteq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoteq_bitwise_or([NotNull] PythonParser.Noteq_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLte_bitwise_or([NotNull] PythonParser.Lte_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLte_bitwise_or([NotNull] PythonParser.Lte_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLt_bitwise_or([NotNull] PythonParser.Lt_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLt_bitwise_or([NotNull] PythonParser.Lt_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.gte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGte_bitwise_or([NotNull] PythonParser.Gte_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.gte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGte_bitwise_or([NotNull] PythonParser.Gte_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.gt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGt_bitwise_or([NotNull] PythonParser.Gt_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.gt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGt_bitwise_or([NotNull] PythonParser.Gt_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.notin_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotin_bitwise_or([NotNull] PythonParser.Notin_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.notin_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotin_bitwise_or([NotNull] PythonParser.Notin_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.in_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIn_bitwise_or([NotNull] PythonParser.In_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.in_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIn_bitwise_or([NotNull] PythonParser.In_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.isnot_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsnot_bitwise_or([NotNull] PythonParser.Isnot_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.isnot_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsnot_bitwise_or([NotNull] PythonParser.Isnot_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.is_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIs_bitwise_or([NotNull] PythonParser.Is_bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.is_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIs_bitwise_or([NotNull] PythonParser.Is_bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwise_or([NotNull] PythonParser.Bitwise_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwise_or([NotNull] PythonParser.Bitwise_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.bitwise_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwise_xor([NotNull] PythonParser.Bitwise_xorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.bitwise_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwise_xor([NotNull] PythonParser.Bitwise_xorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.bitwise_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwise_and([NotNull] PythonParser.Bitwise_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.bitwise_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwise_and([NotNull] PythonParser.Bitwise_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expr([NotNull] PythonParser.Shift_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expr([NotNull] PythonParser.Shift_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum([NotNull] PythonParser.SumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum([NotNull] PythonParser.SumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] PythonParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] PythonParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] PythonParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] PythonParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPower([NotNull] PythonParser.PowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPower([NotNull] PythonParser.PowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.await_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAwait_primary([NotNull] PythonParser.Await_primaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.await_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAwait_primary([NotNull] PythonParser.Await_primaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] PythonParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] PythonParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.slices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlices([NotNull] PythonParser.SlicesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.slices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlices([NotNull] PythonParser.SlicesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlice([NotNull] PythonParser.SliceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlice([NotNull] PythonParser.SliceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] PythonParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] PythonParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] PythonParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] PythonParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdef([NotNull] PythonParser.LambdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdef([NotNull] PythonParser.LambdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_params([NotNull] PythonParser.Lambda_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_params([NotNull] PythonParser.Lambda_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_parameters([NotNull] PythonParser.Lambda_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_parameters([NotNull] PythonParser.Lambda_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_slash_no_default([NotNull] PythonParser.Lambda_slash_no_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_slash_no_default([NotNull] PythonParser.Lambda_slash_no_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_slash_with_default([NotNull] PythonParser.Lambda_slash_with_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_slash_with_default([NotNull] PythonParser.Lambda_slash_with_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_star_etc([NotNull] PythonParser.Lambda_star_etcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_star_etc([NotNull] PythonParser.Lambda_star_etcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_kwds([NotNull] PythonParser.Lambda_kwdsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_kwds([NotNull] PythonParser.Lambda_kwdsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_param_no_default([NotNull] PythonParser.Lambda_param_no_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_param_no_default([NotNull] PythonParser.Lambda_param_no_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_param_with_default([NotNull] PythonParser.Lambda_param_with_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_param_with_default([NotNull] PythonParser.Lambda_param_with_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_param_maybe_default([NotNull] PythonParser.Lambda_param_maybe_defaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_param_maybe_default([NotNull] PythonParser.Lambda_param_maybe_defaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.lambda_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambda_param([NotNull] PythonParser.Lambda_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.lambda_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambda_param([NotNull] PythonParser.Lambda_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_middle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_middle([NotNull] PythonParser.Fstring_middleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_middle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_middle([NotNull] PythonParser.Fstring_middleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_replacement_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_replacement_field([NotNull] PythonParser.Fstring_replacement_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_replacement_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_replacement_field([NotNull] PythonParser.Fstring_replacement_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_conversion([NotNull] PythonParser.Fstring_conversionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_conversion([NotNull] PythonParser.Fstring_conversionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_full_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_full_format_spec([NotNull] PythonParser.Fstring_full_format_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_full_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_full_format_spec([NotNull] PythonParser.Fstring_full_format_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring_format_spec([NotNull] PythonParser.Fstring_format_specContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring_format_spec([NotNull] PythonParser.Fstring_format_specContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.fstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFstring([NotNull] PythonParser.FstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.fstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFstring([NotNull] PythonParser.FstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] PythonParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] PythonParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrings([NotNull] PythonParser.StringsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrings([NotNull] PythonParser.StringsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] PythonParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] PythonParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] PythonParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] PythonParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet([NotNull] PythonParser.SetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet([NotNull] PythonParser.SetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDict([NotNull] PythonParser.DictContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDict([NotNull] PythonParser.DictContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.double_starred_kvpairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble_starred_kvpairs([NotNull] PythonParser.Double_starred_kvpairsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.double_starred_kvpairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble_starred_kvpairs([NotNull] PythonParser.Double_starred_kvpairsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.double_starred_kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble_starred_kvpair([NotNull] PythonParser.Double_starred_kvpairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.double_starred_kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble_starred_kvpair([NotNull] PythonParser.Double_starred_kvpairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKvpair([NotNull] PythonParser.KvpairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKvpair([NotNull] PythonParser.KvpairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.for_if_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_if_clauses([NotNull] PythonParser.For_if_clausesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.for_if_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_if_clauses([NotNull] PythonParser.For_if_clausesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.for_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_if_clause([NotNull] PythonParser.For_if_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.for_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_if_clause([NotNull] PythonParser.For_if_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.listcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListcomp([NotNull] PythonParser.ListcompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.listcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListcomp([NotNull] PythonParser.ListcompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.setcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetcomp([NotNull] PythonParser.SetcompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.setcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetcomp([NotNull] PythonParser.SetcompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.genexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenexp([NotNull] PythonParser.GenexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.genexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenexp([NotNull] PythonParser.GenexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.dictcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictcomp([NotNull] PythonParser.DictcompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.dictcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictcomp([NotNull] PythonParser.DictcompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] PythonParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] PythonParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] PythonParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] PythonParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.kwargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKwargs([NotNull] PythonParser.KwargsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.kwargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKwargs([NotNull] PythonParser.KwargsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.starred_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStarred_expression([NotNull] PythonParser.Starred_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.starred_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStarred_expression([NotNull] PythonParser.Starred_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.kwarg_or_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKwarg_or_starred([NotNull] PythonParser.Kwarg_or_starredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.kwarg_or_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKwarg_or_starred([NotNull] PythonParser.Kwarg_or_starredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.kwarg_or_double_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKwarg_or_double_starred([NotNull] PythonParser.Kwarg_or_double_starredContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.kwarg_or_double_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKwarg_or_double_starred([NotNull] PythonParser.Kwarg_or_double_starredContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_targets([NotNull] PythonParser.Star_targetsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_targets([NotNull] PythonParser.Star_targetsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_targets_list_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_targets_list_seq([NotNull] PythonParser.Star_targets_list_seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_targets_list_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_targets_list_seq([NotNull] PythonParser.Star_targets_list_seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_targets_tuple_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_targets_tuple_seq([NotNull] PythonParser.Star_targets_tuple_seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_targets_tuple_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_targets_tuple_seq([NotNull] PythonParser.Star_targets_tuple_seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_target([NotNull] PythonParser.Star_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_target([NotNull] PythonParser.Star_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.target_with_star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget_with_star_atom([NotNull] PythonParser.Target_with_star_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.target_with_star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget_with_star_atom([NotNull] PythonParser.Target_with_star_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_atom([NotNull] PythonParser.Star_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_atom([NotNull] PythonParser.Star_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.single_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_target([NotNull] PythonParser.Single_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.single_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_target([NotNull] PythonParser.Single_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.single_subscript_attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_subscript_attribute_target([NotNull] PythonParser.Single_subscript_attribute_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.single_subscript_attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_subscript_attribute_target([NotNull] PythonParser.Single_subscript_attribute_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.t_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT_primary([NotNull] PythonParser.T_primaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.t_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT_primary([NotNull] PythonParser.T_primaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.del_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDel_targets([NotNull] PythonParser.Del_targetsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.del_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDel_targets([NotNull] PythonParser.Del_targetsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.del_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDel_target([NotNull] PythonParser.Del_targetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.del_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDel_target([NotNull] PythonParser.Del_targetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.del_t_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDel_t_atom([NotNull] PythonParser.Del_t_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.del_t_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDel_t_atom([NotNull] PythonParser.Del_t_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.type_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_expressions([NotNull] PythonParser.Type_expressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.type_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_expressions([NotNull] PythonParser.Type_expressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.func_type_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_type_comment([NotNull] PythonParser.Func_type_commentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.func_type_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_type_comment([NotNull] PythonParser.Func_type_commentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.soft_kw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoft_kw_type([NotNull] PythonParser.Soft_kw_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.soft_kw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoft_kw_type([NotNull] PythonParser.Soft_kw_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.soft_kw_match"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoft_kw_match([NotNull] PythonParser.Soft_kw_matchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.soft_kw_match"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoft_kw_match([NotNull] PythonParser.Soft_kw_matchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.soft_kw_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoft_kw_case([NotNull] PythonParser.Soft_kw_caseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.soft_kw_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoft_kw_case([NotNull] PythonParser.Soft_kw_caseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.soft_kw_wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoft_kw_wildcard([NotNull] PythonParser.Soft_kw_wildcardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.soft_kw_wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoft_kw_wildcard([NotNull] PythonParser.Soft_kw_wildcardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PythonParser.soft_kw__not__wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSoft_kw__not__wildcard([NotNull] PythonParser.Soft_kw__not__wildcardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PythonParser.soft_kw__not__wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSoft_kw__not__wildcard([NotNull] PythonParser.Soft_kw__not__wildcardContext context);
}
} // namespace GameVM.Compiler.Python.ANTLR
