//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PythonParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GameVM.Compiler.Python.ANTLR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PythonParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPythonParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.file_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_input([NotNull] PythonParser.File_inputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.interactive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteractive([NotNull] PythonParser.InteractiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEval([NotNull] PythonParser.EvalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.func_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_type([NotNull] PythonParser.Func_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_input([NotNull] PythonParser.Fstring_inputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] PythonParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PythonParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.statement_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_newline([NotNull] PythonParser.Statement_newlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.simple_stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_stmts([NotNull] PythonParser.Simple_stmtsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.simple_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_stmt([NotNull] PythonParser.Simple_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.compound_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_stmt([NotNull] PythonParser.Compound_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] PythonParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.annotated_rhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotated_rhs([NotNull] PythonParser.Annotated_rhsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.augassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAugassign([NotNull] PythonParser.AugassignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_stmt([NotNull] PythonParser.Return_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.raise_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise_stmt([NotNull] PythonParser.Raise_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.global_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_stmt([NotNull] PythonParser.Global_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.nonlocal_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonlocal_stmt([NotNull] PythonParser.Nonlocal_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.del_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDel_stmt([NotNull] PythonParser.Del_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.yield_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYield_stmt([NotNull] PythonParser.Yield_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.assert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssert_stmt([NotNull] PythonParser.Assert_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_stmt([NotNull] PythonParser.Import_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_name([NotNull] PythonParser.Import_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_from([NotNull] PythonParser.Import_fromContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_from_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_from_targets([NotNull] PythonParser.Import_from_targetsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_from_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_from_as_names([NotNull] PythonParser.Import_from_as_namesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.import_from_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_from_as_name([NotNull] PythonParser.Import_from_as_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.dotted_as_names"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotted_as_names([NotNull] PythonParser.Dotted_as_namesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.dotted_as_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotted_as_name([NotNull] PythonParser.Dotted_as_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.dotted_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotted_name([NotNull] PythonParser.Dotted_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] PythonParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.decorators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecorators([NotNull] PythonParser.DecoratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.class_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_def([NotNull] PythonParser.Class_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.class_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_def_raw([NotNull] PythonParser.Class_def_rawContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.function_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_def([NotNull] PythonParser.Function_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.function_def_raw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_def_raw([NotNull] PythonParser.Function_def_rawContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] PythonParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] PythonParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlash_no_default([NotNull] PythonParser.Slash_no_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlash_with_default([NotNull] PythonParser.Slash_with_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_etc([NotNull] PythonParser.Star_etcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKwds([NotNull] PythonParser.KwdsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_no_default([NotNull] PythonParser.Param_no_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param_no_default_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_no_default_star_annotation([NotNull] PythonParser.Param_no_default_star_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_with_default([NotNull] PythonParser.Param_with_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_maybe_default([NotNull] PythonParser.Param_maybe_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] PythonParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.param_star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_star_annotation([NotNull] PythonParser.Param_star_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] PythonParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_annotation([NotNull] PythonParser.Star_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.default_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_assignment([NotNull] PythonParser.Default_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] PythonParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.elif_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElif_stmt([NotNull] PythonParser.Elif_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_block([NotNull] PythonParser.Else_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] PythonParser.While_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_stmt([NotNull] PythonParser.For_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.with_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_stmt([NotNull] PythonParser.With_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.with_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_item([NotNull] PythonParser.With_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.try_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTry_stmt([NotNull] PythonParser.Try_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.except_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExcept_block([NotNull] PythonParser.Except_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.except_star_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExcept_star_block([NotNull] PythonParser.Except_star_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.finally_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinally_block([NotNull] PythonParser.Finally_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.match_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatch_stmt([NotNull] PythonParser.Match_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.subject_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubject_expr([NotNull] PythonParser.Subject_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.case_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_block([NotNull] PythonParser.Case_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuard([NotNull] PythonParser.GuardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatterns([NotNull] PythonParser.PatternsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern([NotNull] PythonParser.PatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.as_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_pattern([NotNull] PythonParser.As_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.or_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_pattern([NotNull] PythonParser.Or_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.closed_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosed_pattern([NotNull] PythonParser.Closed_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.literal_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_pattern([NotNull] PythonParser.Literal_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.literal_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_expr([NotNull] PythonParser.Literal_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.complex_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplex_number([NotNull] PythonParser.Complex_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_number([NotNull] PythonParser.Signed_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.signed_real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_real_number([NotNull] PythonParser.Signed_real_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.real_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReal_number([NotNull] PythonParser.Real_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.imaginary_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImaginary_number([NotNull] PythonParser.Imaginary_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.capture_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture_pattern([NotNull] PythonParser.Capture_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.pattern_capture_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern_capture_target([NotNull] PythonParser.Pattern_capture_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.wildcard_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWildcard_pattern([NotNull] PythonParser.Wildcard_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_pattern([NotNull] PythonParser.Value_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttr([NotNull] PythonParser.AttrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.name_or_attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_or_attr([NotNull] PythonParser.Name_or_attrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.group_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_pattern([NotNull] PythonParser.Group_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence_pattern([NotNull] PythonParser.Sequence_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.open_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpen_sequence_pattern([NotNull] PythonParser.Open_sequence_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.maybe_sequence_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaybe_sequence_pattern([NotNull] PythonParser.Maybe_sequence_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.maybe_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMaybe_star_pattern([NotNull] PythonParser.Maybe_star_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_pattern([NotNull] PythonParser.Star_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.mapping_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapping_pattern([NotNull] PythonParser.Mapping_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.items_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItems_pattern([NotNull] PythonParser.Items_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.key_value_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey_value_pattern([NotNull] PythonParser.Key_value_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.double_star_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_star_pattern([NotNull] PythonParser.Double_star_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.class_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_pattern([NotNull] PythonParser.Class_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.positional_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositional_patterns([NotNull] PythonParser.Positional_patternsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.keyword_patterns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword_patterns([NotNull] PythonParser.Keyword_patternsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.keyword_pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword_pattern([NotNull] PythonParser.Keyword_patternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_alias([NotNull] PythonParser.Type_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_params([NotNull] PythonParser.Type_paramsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_param_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_param_seq([NotNull] PythonParser.Type_param_seqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_param([NotNull] PythonParser.Type_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_param_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_param_bound([NotNull] PythonParser.Type_param_boundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressions([NotNull] PythonParser.ExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] PythonParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.yield_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYield_expr([NotNull] PythonParser.Yield_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_expressions([NotNull] PythonParser.Star_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_expression([NotNull] PythonParser.Star_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_named_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_named_expressions([NotNull] PythonParser.Star_named_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_named_expression([NotNull] PythonParser.Star_named_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_expression([NotNull] PythonParser.Assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.named_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_expression([NotNull] PythonParser.Named_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisjunction([NotNull] PythonParser.DisjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConjunction([NotNull] PythonParser.ConjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.inversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInversion([NotNull] PythonParser.InversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] PythonParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.compare_op_bitwise_or_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare_op_bitwise_or_pair([NotNull] PythonParser.Compare_op_bitwise_or_pairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.eq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEq_bitwise_or([NotNull] PythonParser.Eq_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.noteq_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoteq_bitwise_or([NotNull] PythonParser.Noteq_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLte_bitwise_or([NotNull] PythonParser.Lte_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLt_bitwise_or([NotNull] PythonParser.Lt_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.gte_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGte_bitwise_or([NotNull] PythonParser.Gte_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.gt_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGt_bitwise_or([NotNull] PythonParser.Gt_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.notin_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotin_bitwise_or([NotNull] PythonParser.Notin_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.in_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_bitwise_or([NotNull] PythonParser.In_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.isnot_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsnot_bitwise_or([NotNull] PythonParser.Isnot_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.is_bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIs_bitwise_or([NotNull] PythonParser.Is_bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.bitwise_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwise_or([NotNull] PythonParser.Bitwise_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.bitwise_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwise_xor([NotNull] PythonParser.Bitwise_xorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.bitwise_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwise_and([NotNull] PythonParser.Bitwise_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expr([NotNull] PythonParser.Shift_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSum([NotNull] PythonParser.SumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] PythonParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] PythonParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower([NotNull] PythonParser.PowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.await_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAwait_primary([NotNull] PythonParser.Await_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] PythonParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.slices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlices([NotNull] PythonParser.SlicesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.slice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlice([NotNull] PythonParser.SliceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] PythonParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] PythonParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdef([NotNull] PythonParser.LambdefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_params([NotNull] PythonParser.Lambda_paramsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_parameters([NotNull] PythonParser.Lambda_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_slash_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_slash_no_default([NotNull] PythonParser.Lambda_slash_no_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_slash_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_slash_with_default([NotNull] PythonParser.Lambda_slash_with_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_star_etc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_star_etc([NotNull] PythonParser.Lambda_star_etcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_kwds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_kwds([NotNull] PythonParser.Lambda_kwdsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_param_no_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_param_no_default([NotNull] PythonParser.Lambda_param_no_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_param_with_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_param_with_default([NotNull] PythonParser.Lambda_param_with_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_param_maybe_default"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_param_maybe_default([NotNull] PythonParser.Lambda_param_maybe_defaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.lambda_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_param([NotNull] PythonParser.Lambda_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_middle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_middle([NotNull] PythonParser.Fstring_middleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_replacement_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_replacement_field([NotNull] PythonParser.Fstring_replacement_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_conversion([NotNull] PythonParser.Fstring_conversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_full_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_full_format_spec([NotNull] PythonParser.Fstring_full_format_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring_format_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring_format_spec([NotNull] PythonParser.Fstring_format_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.fstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFstring([NotNull] PythonParser.FstringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] PythonParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.strings"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrings([NotNull] PythonParser.StringsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] PythonParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple([NotNull] PythonParser.TupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] PythonParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.dict"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDict([NotNull] PythonParser.DictContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.double_starred_kvpairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_starred_kvpairs([NotNull] PythonParser.Double_starred_kvpairsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.double_starred_kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_starred_kvpair([NotNull] PythonParser.Double_starred_kvpairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.kvpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKvpair([NotNull] PythonParser.KvpairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.for_if_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_if_clauses([NotNull] PythonParser.For_if_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.for_if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_if_clause([NotNull] PythonParser.For_if_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.listcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListcomp([NotNull] PythonParser.ListcompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.setcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetcomp([NotNull] PythonParser.SetcompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.genexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenexp([NotNull] PythonParser.GenexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.dictcomp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictcomp([NotNull] PythonParser.DictcompContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] PythonParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] PythonParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.kwargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKwargs([NotNull] PythonParser.KwargsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.starred_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStarred_expression([NotNull] PythonParser.Starred_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.kwarg_or_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKwarg_or_starred([NotNull] PythonParser.Kwarg_or_starredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.kwarg_or_double_starred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKwarg_or_double_starred([NotNull] PythonParser.Kwarg_or_double_starredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_targets([NotNull] PythonParser.Star_targetsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_targets_list_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_targets_list_seq([NotNull] PythonParser.Star_targets_list_seqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_targets_tuple_seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_targets_tuple_seq([NotNull] PythonParser.Star_targets_tuple_seqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_target([NotNull] PythonParser.Star_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.target_with_star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget_with_star_atom([NotNull] PythonParser.Target_with_star_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.star_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_atom([NotNull] PythonParser.Star_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.single_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_target([NotNull] PythonParser.Single_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.single_subscript_attribute_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_subscript_attribute_target([NotNull] PythonParser.Single_subscript_attribute_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.t_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitT_primary([NotNull] PythonParser.T_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.del_targets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDel_targets([NotNull] PythonParser.Del_targetsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.del_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDel_target([NotNull] PythonParser.Del_targetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.del_t_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDel_t_atom([NotNull] PythonParser.Del_t_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.type_expressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_expressions([NotNull] PythonParser.Type_expressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.func_type_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_type_comment([NotNull] PythonParser.Func_type_commentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.soft_kw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoft_kw_type([NotNull] PythonParser.Soft_kw_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.soft_kw_match"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoft_kw_match([NotNull] PythonParser.Soft_kw_matchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.soft_kw_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoft_kw_case([NotNull] PythonParser.Soft_kw_caseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.soft_kw_wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoft_kw_wildcard([NotNull] PythonParser.Soft_kw_wildcardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PythonParser.soft_kw__not__wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoft_kw__not__wildcard([NotNull] PythonParser.Soft_kw__not__wildcardContext context);
}
} // namespace GameVM.Compiler.Python.ANTLR
